### ISSUE TITLE
Getting a crash at the startup of any heist.

### ISSUE THREAD

**Issue by Niceguy13311** [segabl/pd2-npc-weapon-customizer#2]
https://pastebin.com/61k5i1mQ

I've had nothing enabled but HQ weapons for jokers and specials. Also firing animations.

**Comment by segabl** [comment]
I'm looking into it, happens because of Team AI

**Comment by segabl** [comment]
Should be fixed with https://github.com/segabl/pd2-npc-weapon-customizer/commit/c6eefa0209a35092073ae47c953156967c2d6678

**Comment by Niceguy13311** [comment]
Okay, thanks!
