### ISSUE TITLE
Custom charms don't work on NPC weapons

### ISSUE THREAD

**Issue by milodakat** [segabl/pd2-npc-weapon-customizer#6]
Any modded charm on a weapon (at least the ones I tested) makes that weapon unequippable with NPC weapon customizer.

**Comment by segabl** [comment]
because custom charms don't have a third_unit, which is required for third person models. this is more of a quirk with how the game sets up the charms data, as beardlib does not copy the third_unit from the based on charm, since that doesn't exist at the point the custom charm is created.

**Comment by milodakat** [comment]
Is this a beardlib issue or (unfixable?) game issue

**Comment by segabl** [comment]
Well it is certainly fixable, it's kinda a BeardLib issue but at the same time not, since charms are handled like weapon mods (which BeardLib works fine with) but are not created at the same time as weapon mods which makes BeardLib not find the "based_on" charm to copy data (third_unit) from.
